# Generated by Django 2.1.2 on 2018-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginlogout', '0002_users_iflogged'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
